### ISSUE TITLE
"ModuleNotFound" error when importing "plot_miller_ground_track" 

### ISSUE THREAD

**Issue by pietrosilvagni** [tudat-team/tudatpy#61]
When importing "plot_miller_ground_track" using this line:

" from tudatpy.plotting import plot_miller_ground_track "

The following error is shown:

" from mpl_toolkits.basemap import Basemap

ModuleNotFoundError: No module named 'mpl_toolkits.basemap' "

I have already discussed this with Dominic, and it looks like this error message is due to a bug.

**Comment by geoffreygarrett** [comment]
@gaffarelj & @DominicDirkx, this is ideally fixed by adding `matplotlib` and `basemap` to [this list here](https://github.com/tudat-team/tudatpy-feedstock/blob/a6ff15ca05c2231347a619d12ba5df79aab87bcd/recipe/meta.yaml#L59) in the feedstock. If I understand correctly, `matplotlib` is currently installed via an environment file which includes `tudatpy` for the courses. Since `tudatpy` has a `matplotlib` dependency for its plotting module, we should rather add the dependencies to the conda package itself.

**Comment by geoffreygarrett** [comment]
Also, to add a test during the conda packaging, `tudatpy.plotting.plot_miller_ground_track` can be added [here](https://github.com/tudat-team/tudatpy-feedstock/blob/a6ff15ca05c2231347a619d12ba5df79aab87bcd/recipe/meta.yaml#L71), which will test the function by simply importing it, catching what @pietrosilvagni encountered.

**Comment by gaffarelj** [comment]
I made the appropriate changes with [this commit](597d2e4c9a4918d024e651cc1bccdb97255addf5).

@pietrosilvagni in your case, instead of re-installing tudatpy when the next conda package is released, you can run the following two lines in the conda environment in which you use tudatpy:
````
conda install matplotlib
conda install basemap
````
